language: python
python:
  - "3.5"
# command to install dependencies
install: 
    - pip install -r requirements.txt
    - pip install coveralls
# command to run tests
script: 
    - coverage run --source=wisewebspider/main.py test

# run coveralls
after_success:
    coveralls
